version: '2'
services:
  api:
    image: "[YOUR API IMAGE PATH]"
    ports:
     - "80:80"
    depends_on:
     - "sqlserver"
  sqlserver:
    image: "microsoft/mssql-server-linux"
    ports:
      ["1433:1433"]
    environment:
      SA_PASSWORD: P@55w0rd
      ACCEPT_EULA: Y